version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    networks:
      - n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true

  ollama:
    image: ollama-docker:v2
    networks:
      - n8n
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - n8n

networks:
  n8n:
    driver: bridge

volumes:
  n8n_data:

